In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn 

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
from sklearn.datasets import load_iris


In [3]:
x,y=load_iris(return_X_y=True)
pd.DataFrame(x)


0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [5]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20)


In [6]:
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)



KNeighborsClassifier()

In [7]:
y_pred=classifier.predict(x_test)
y_pred

C:\Users\ACER\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([1, 2, 0, 1, 0, 2, 2, 2, 0, 1, 2, 1, 2, 0, 1, 0, 1, 2, 0, 0, 0, 0,
       1, 1, 2, 2, 1, 2, 1, 0])

In [8]:
y_test


array([1, 2, 0, 1, 0, 2, 2, 2, 0, 1, 2, 1, 2, 0, 1, 0, 1, 2, 0, 0, 0, 0,
       1, 1, 2, 2, 1, 2, 1, 0])

In [10]:
cm=confusion_matrix(y_test,y_pred)
cm


array([[12,  0,  0],
       [ 0,  5,  2],
       [ 0,  0, 11]], dtype=int64)

In [11]:
ac=accuracy_score(y_test,y_pred)
ac


0.9333333333333333

In [12]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.71      0.83         7
           2       0.85      1.00      0.92        11

    accuracy                           0.93        30
   macro avg       0.95      0.90      0.92        30
weighted avg       0.94      0.93      0.93        30

